### ISSUE TITLE
Using personal API

### ISSUE THREAD

**Issue by y1zhou** [Wox-launcher/Wox.Plugin.Youdao#10]
Is there any possibility that one can use his own Youdao API rather than the built-in one? The plugin is constantly stuck now, and I assume this is caused by the overuse of a single API.

Thanks for the awesome plugin!

**Comment by luantu** [comment]
直接自己申请个授权  编译下就是了。
https://github.com/Selection-Translator/crx-selection-translate/wiki/%E7%94%B3%E8%AF%B7%E6%9C%89%E9%81%93%E7%BF%BB%E8%AF%91-API

**Comment by pengzhxyz** [comment]
Hi, please try my private-key version fork: [有道翻译私Key版](http://www.getwox.com/plugin/151) and github repo: [Wox.Plugin.Youdao](https://github.com/pengzhxyz/Wox.Plugin.Youdao). It does:

* allow you to use your own Youdao api key(also have to) to avoid overuse of the built-in api key.
* use new Youdao api([ai.youdao.com](http://ai.youdao.com)), because the old api will be stopped by 2017-12-31 as declaring by Youdao. 

Note:

1. `wpm uninstall 有道翻译` and than `wpm install 有道翻译私Key版`.
2. bind your own youdao AppKey and SecretKey in the plugin setting.

**Comment by alonWang** [comment]
增加一点说明 : 有道智云需要创建翻译示例和应用示例,并将翻译实例绑定到应用.应用上的appID即为插件中需要这设置的appKey
